# Generated by Django 4.2 on 2023-05-01 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100, unique=True)),
                ("mobileno", models.CharField(max_length=50, null=True)),
                ("picture", models.CharField(max_length=200, null=True)),
                ("qrcodeurl", models.CharField(max_length=200, null=True)),
                ("isblocked", models.IntegerField(default=0)),
                ("mailtoken", models.IntegerField(default=0)),
                ("secretkey", models.CharField(max_length=70, null=True)),                
            ],
        ),
    ]
