# Generated by Django 4.2 on 2023-05-01 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descriptions", models.CharField(max_length=255, null=True)),
                ("qty", models.IntegerField(default=0)),
                ("unit", models.CharField(max_length=50, null=True)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("sell_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prod_pic", models.CharField(max_length=100, null=True)),
                ("category", models.CharField(max_length=50, null=True)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("alert_level", models.IntegerField(default=0)),
                ("critical_level", models.IntegerField(default=0)),
                (
                    "datecreated",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 1, 9, 13, 29, 229126)
                    ),
                ),
                (
                    "dateupdated",
                    models.DateTimeField(
                        default=datetime.datetime(2023, 5, 1, 9, 13, 29, 229148)
                    ),
                ),
            ],
        ),
    ]
